### ISSUE TITLE
Code for SwarmBrain paper

### ISSUE THREAD

**Issue by FennFlyer** [ramsayxiaoshao/SwarmBrain#1]
Hello! Are there plans to push the code to accompany the SwarmBrain paper? I would love to test an implementation with either Terran or Protoss. This is a great paper, thanks for publishing!

**Comment by ramsayxiaoshao** [comment]
Dear FennFlyer,
We are preparing to release the code ASAP, but it involves many company policy issues. We are communicating with the company through the innovation leader and will upload the code once approved.
